export interface IJob {
  id: string,
  timestamp?: string,
  zeitstempel: string,
  source: string,
  header: string,
  content: string,
  language: string,
  experience_level: string,
  employment_type: string,
  poster: string,
  application_link: string,
  company_name: string,
  location: string,
  deadline: string,
  redi_community_only: string,
  contact_name: string,
}
