export interface IJob {
  id: string,
  timestamp: string,
  source: string,
  header: string,
  content: string,
  language: string,
  experience: string,
  employment_time: string,
  poster: string,
  application_link: string,
  company_name: string,
  location: string,
  deadline: string,
  community_only: string,
  contact_name: string,
}
